server:
  port: ${PORT:8080}
  servlet:
    context-path: /bookstore

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

spring:
  datasource:
    url: "${mysql_url}"
    username: "${mysql_username}"
    password: "${mysql_password}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  spring:
    autoconfigure:
       exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchAutoConfiguration

  data:
    mongodb:
      uri: "${mongoDB_uri}"
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

jwt:
  signerKey: "${signer_key}"

cloudinary:
  cloud-name: dfinfmcan
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET} 

stripe:
  apiKey: ${STRIPE_KEY}
openai:
  api:
    key: ${OPENAI_API_KEY}
